using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using Mono.Cecil;
using Nule.Packet;
using UnityEditor;

namespace Nule.Weaver
{
    [InitializeOnLoad]
    public static class Definitions
    {
        private static Dictionary<string, MethodDefinition> _rpcMethodsDefinitions = new();
        private static Dictionary<int, NetworkBehaviour> _networkObjectInstances = new();
        
        //CsAssembly is the dll generated by Unity with all User's types.
        public static Assembly CsAssembly => Assembly.GetExecutingAssembly();
        
        public static string[] UnityAssemblies => new[]
        {
            Path.GetFullPath(@"..\..\Editor\Data\Managed\UnityEngine.dll"),
            Path.GetFullPath(@"..\..\Editor\Data\Managed\UnityEngine\UnityEngine.CoreModule.dll")
        };
        
        public static Type RpcAttribute => typeof(RpcAttribute);
        public static Type NetworkBehaviour => typeof(NetworkBehaviour);

        internal static Dictionary<string, MethodDefinition> RpcMethodsDefinitions => _rpcMethodsDefinitions;
        internal static Dictionary<int, NetworkBehaviour> NetworkObjectInstances => _networkObjectInstances;
    }
}


